name: check

on: [push, pull_request]

env:
  NODE_VERSION: 16


jobs:
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: npm run eslint
      - run: npm run test